### ISSUE TITLE
callback was already called

### ISSUE THREAD

**Issue by danverde** [byuitechops/match-question-answers#4]
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:955
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:955:32
    at canvas.getQuizQuestions (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\match-question-answers\main.js:53:21)
    at Request.request.get [as _callback] (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:139:13)
    at Request.self.callback (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:1085:12)

**Comment by csammcgrath** [comment]
This bug should be fixed now with the update to the code. Can you please run the tool and let me know the results? Thanks!

**Comment by csammcgrath** [comment]
Fixed.
